name: auto-dist
on:
  push:
    branches:
      - 'master'

jobs:
  auto-dist:
    runs-on: ubuntu-latest
    steps:
      - name: clone
        run: |
          git clone https://${{secrets.ACTIONTOKEN}}@github.com/zsummer/zbase.git zbase-master
          git clone https://${{secrets.ACTIONTOKEN}}@github.com/zsummer/zbase.git -b dist zbase-dist
          ls
          cd zbase-master
          git config --global user.email "yawei.zhang@foxmail.com"
          git config --global user.name "zsummer"
          git status
          cd ../zbase-dist
          git config --global user.email "yawei.zhang@foxmail.com"
          git config --global user.name "zsummer"
          git status
      - name: local-dist
        run: |
          cd zbase-master
          bash distribute.sh 
          git add *
          git commit -a --allow-empty -m "[skip ci] auto dist"  
          git push 
      - name: branch-dist
        run: |
          cd zbase-master
          cp -r dist/* ../zbase-dist/
          cd ../zbase-dist/
          git status
          git add *
          git diff --cached |wc -l
          git commit -a --allow-empty -m "[skip ci]auto dist"  
          git push 
          
